extends RefCounted

## Tre tappe autoriali per riparazione: lettura del problema, azione, verifica.
## I dati corretti sono ripresentati: un errore non altera la prova successiva.
static func nodes_for(world: int, variant: int = 0) -> Array:
	var v := posmod(variant, 2)
	var nodes: Array = []
	match world:
		2:
			var windows := 3 + v
			nodes = [
				_order("italiano", "testo-narrativo", "Il diario di Stilo racconta: le rondini entrarono; più tardi il vento chiuse le finestre; infine Stilo cercò la chiave. Ricostruisci gli eventi per capire quando rimasero intrappolate.", ["Le rondini entrano", "Il vento chiude le finestre", "Stilo cerca la chiave"], "Prima entrano gli animali, poi si chiude l'uscita: la ricerca della chiave è una conseguenza.", "Il diario interrotto", "Le rondini sono dentro: dobbiamo riaprire le finestre.", "In un racconto, prima, poi e infine collegano gli eventi. Il rimedio segue il problema che lo rende necessario."),
				_num("matematica", "tabelline", "Il diario ci ha indicato le finestre da riaprire: sono %d. Ognuna ha due fermi bloccati. Quanti fermi dobbiamo liberare in tutto?" % windows, windows * 2, "Ogni finestra aggiunge un gruppo di due: %d × 2 = %d fermi." % [windows, windows * 2], "I fermi delle finestre", "I fermi sono liberi. Le ante possono aprirsi.", "Tre sportelli con due cerniere ciascuno hanno 2 + 2 + 2 cerniere: conta un gruppo per ogni sportello."),
				_order("italiano", "tipologie-testuali", "I fermi sono liberi. Il cartello prescrive: prima aprire le ante; soltanto dopo che le rondini sono uscite controllare i nidi. Ordina il protocollo senza spaventare gli animali.", ["Aprire le ante", "Aspettare che le rondini escano", "Controllare i nidi dall'esterno"], "Il controllo viene dopo l'uscita; aprire crea il passaggio necessario alle rondini.", "Una via verso il cielo", "Le finestre si riaprono e le rondini tornano a volare.", "Un testo di istruzioni lega azioni e condizioni: 'soltanto dopo' impedisce di anticipare un passaggio."),
			]
		3:
			var rounds := 3 + v
			nodes = [
				_order("coding", "cicli", "Telaio ha lasciato la regola del contatore: esegui il gesto, aumenta il numero dei giri, poi controlla se hai finito. La macchina ripete sempre il terzo giro perché il contatore non viene aggiornato. Rimetti in ordine le tre istruzioni del giro.", ["Esegui il gesto", "Aumenta il contatore di 1", "Controlla se hai raggiunto il limite"], "Il contatore deve cambiare prima della verifica; altrimenti la macchina legge ogni volta lo stesso numero.", "Il giro che non finisce", "Il contatore avanza di nuovo: ora possiamo impostare il limite.", "Un ciclo ripete istruzioni. Se il suo contatore aumenta di uno a ogni giro, la verifica vede il progresso."),
				_num("matematica", "tabelline", "Il contatore riparato deve eseguire %d giri. Ogni giro della macchina produce due impulsi. Quanti impulsi deve contare il sensore prima dell'arresto?" % rounds, rounds * 2, "%d gruppi di due impulsi danno %d impulsi totali." % [rounds, rounds * 2], "Il limite del sensore", "Il limite è impostato a %d impulsi." % (rounds * 2), "Per passare dai giri agli impulsi, ripeti il numero di impulsi di un giro per tutti i giri."),
				_mc("coding", "condizioni", "Il limite del sensore è %d impulsi. Il test arriva esattamente a quel valore. La regola è: ripeti finché il conteggio è MINORE del limite. Che cosa deve fare adesso?" % (rounds * 2), "Fermarsi", ["Ripetere un altro giro", "Azzerarsi e ripartire subito"], "Al limite il conteggio non è più minore: la condizione è falsa e il ciclo termina.", "La prova d'arresto", "La macchina completa il ciclo e resta pronta per un nuovo avvio.", "'Minore di' esclude l'uguaglianza: 4 è minore di 5, mentre 5 non è minore di 5."),
			]
		4:
			var bays := 3 + v
			nodes = [
				_match("inglese", "safety", "Sul molo di Faro i comandi sono in inglese. Associa ogni comando all'azione: serviranno per isolare il braciere e attivare il sistema automatico.", [["Keep back", "Resta indietro"], ["Close the gate", "Chiudi il cancello"], ["Start the pump", "Avvia la pompa"]], "Keep back protegge la zona, close chiude e start avvia: sono comandi con azioni diverse.", "I comandi di Faro", "Ora sappiamo leggere i comandi del sistema del molo.", "Nei comandi inglesi il verbo indica l'azione: close significa chiudere, start avviare; keep back chiede di mantenere la distanza."),
				_order("logica", "deduzioni", "Hai tradotto i comandi. Due blocchi impediscono errori: il cancello può chiudersi soltanto quando tutti sono arretrati; la pompa parte soltanto col cancello chiuso. Ordina le azioni possibili.", ["Keep back", "Close the gate", "Start the pump"], "La pompa dipende dal cancello e il cancello dall'arretramento: i due vincoli fissano l'intero ordine.", "La sequenza protetta", "La zona è isolata e la pompa è pronta.", "Se C richiede B e B richiede A, devi completare A, poi B, poi C."),
				_num("matematica", "problemi", "La pompa avviata alimenta %d ugelli automatici. Ciascuno richiede 2 unità d'acqua; il serbatoio ne contiene 12. Quante unità resteranno dopo un'attivazione di tutti gli ugelli?" % bays, 12 - bays * 2, "Prima calcola il consumo: %d × 2. Poi sottrai quel consumo dalle 12 unità disponibili." % bays, "Acqua per tutto il molo", "Gli ugelli completano l'intervento e le boe tornano a rispondere.", "Se tre strumenti consumano quattro unità ciascuno, insieme consumano dodici unità. La riserva è disponibilità meno consumo."),
			]
		5:
			var load := 12 + 4 * v
			nodes = [
				_mc("fisica", "leve", "La grande leva è bloccata. Nel modello di Leva, il carico agisce a 1 metro dal fulcro e tu spingi dal lato opposto a 2 metri. Quale forza basta per equilibrare il carico?", "Metà della forza del carico", ["Il doppio della forza del carico", "La forza del carico più 2"], "Per l'equilibrio, forza × distanza deve coincidere sui due lati. Una distanza doppia permette una forza dimezzata.", "Il fulcro ritrovato", "Il fulcro è riallineato: il tuo braccio misura il doppio di quello del carico.", "In una leva ideale conta il prodotto forza per distanza dal fulcro. 3 N a 4 m equilibrano 6 N a 2 m; trascuriamo peso della leva e attriti."),
				_num("matematica", "divisioni", "Usiamo il rapporto appena trovato. Il carico esercita %d N a 1 m dal fulcro; il braccio della spinta è 2 m. Quanti newton equilibrano la leva?" % load, load / 2, "La forza cercata moltiplicata per 2 m deve dare %d N·m: servono %d N." % [load, load / 2], "La forza necessaria", "Il regolatore è tarato sulla forza di equilibrio.", "Per trovare un fattore sconosciuto dividi il prodotto per l'altro fattore. Se F × 3 = 18, allora F = 18 ÷ 3."),
				_order("fisica", "leve", "La forza trovata vale con un braccio di 2 m. Per alzare il blocco il regolatore aggiunge poi una piccola spinta. Ordina i tre punti di spinta, dal più vicino al più lontano dal fulcro: ottieni il passaggio dalla forza necessaria maggiore alla minore.", ["Punto a 1 m", "Punto a 2 m", "Punto a 3 m"], "A parità di carico, allontanare la spinta dal fulcro aumenta il suo braccio e riduce la forza di equilibrio necessaria.", "La prova della rampa", "La leva solleva il blocco e libera la rampa.", "Con il carico fermo nello stesso punto, un braccio di spinta più lungo riduce lo sforzo. Equilibrare non significa ancora iniziare il sollevamento."),
			]
		6:
			var measures := 3 + v
			nodes = [
				_match("musica", "ritmo", "Corda ha segnato le durate per l'albero. In questa partitura la semiminima vale un battito. Ricostruisci la legenda che useremo per regolare gli impulsi.", [["Semiminima", "1 battito"], ["Minima", "2 battiti"], ["Semibreve", "4 battiti"]], "La minima dura due semiminime; la semibreve dura due minime, cioè quattro semiminime.", "La legenda di Corda", "Le durate dei segni sono leggibili: possiamo controllare la battuta.", "Con la semiminima come unità, una minima dura due battiti e una semibreve quattro. Il tempo della musica determina quanto dura ciascun battito."),
				_num("matematica", "problemi", "Usa la legenda: ogni battuta dell'albero contiene una minima e due semiminime. Il regolatore deve suonare %d battute. Quanti battiti deve emettere?" % measures, measures * 4, "Una battuta dura 2 + 1 + 1 = 4 battiti. Ripetila %d volte: %d battiti." % [measures, measures * 4], "Il regolatore degli impulsi", "Il regolatore conosce la durata dell'intera frase.", "Calcola prima la durata di un gruppo, poi moltiplica per il numero di gruppi."),
				_mc("musica", "tempo", "La frase ha %d battiti. Al test, gli impulsi sono troppo lenti: arrivano a 60 battiti al minuto; Corda richiede 120. Che cosa cambiamo mantenendo lo stesso ritmo scritto?" % (measures * 4), "Dimezziamo il tempo tra due battiti", ["Raddoppiamo il tempo tra due battiti", "Togliamo metà delle note"], "120 battiti al minuto sono il doppio di 60: ogni battito dura metà del tempo, mentre i rapporti fra le durate delle note restano uguali.", "Il respiro dell'albero", "L'albero ritrova il tempo e le terrazze si illuminano a ogni battuta.", "I battiti al minuto misurano la velocità della pulsazione. Aumentarli accelera tutti i valori ritmici nello stesso rapporto."),
			]
		7:
			var slabs := 6 + 2 * v
			nodes = [
				_match("latino", "casi", "Radice ha annotato PORTAM, MURI e LUCERTAE. Nel suo registro la legenda dice: portam è accusativo singolare di porta; muri è genitivo singolare di murus; lucertae è nominativo plurale di lucerta. Associa ciascuna forma al ruolo che avrà nella lettura dell'ordine.", [["PORTAM: accusativo", "L'oggetto su cui agire"], ["MURI: genitivo", "Specifica di quale struttura"], ["LUCERTAE: nominativo", "Gli animali che compiono l'azione"]], "Nel registro, l'accusativo individua la porta come oggetto, il genitivo la collega al muro e il nominativo indica le lucertole come soggetto.", "I casi sulla pietra", "La porta del muro è il passaggio; le lucertole devono attraversarlo.", "Qui usiamo tre funzioni: soggetto al nominativo, oggetto all'accusativo e specificazione al genitivo. Una forma isolata può essere ambigua: le indicazioni del registro fissano caso e numero."),
				_mc("logica", "esclusioni", "La lettura indica la porta del muro. Ci sono tre pannelli: A è parte dell'arco portante; B chiude il passaggio delle lucertole; C protegge le iscrizioni. Radice vieta di toccare l'arco e chiede di conservare la protezione delle iscrizioni. Quale pannello possiamo rimuovere?", "B", ["A", "C"], "A viola il vincolo strutturale e C quello di protezione. B libera il passaggio senza violare nessuno dei due.", "Il varco giusto", "È stato individuato il pannello B: arco e iscrizioni restano protetti.", "Una scelta deve rispettare tutti i vincoli insieme: scarta un'opzione appena ne viola uno."),
				_num("matematica", "problemi", "Il pannello B scelto contiene %d lastre. Il sollevatore porta 2 lastre per viaggio. Il carrello ha già compiuto 1 viaggio pieno: quanti viaggi pieni restano per aprire il passaggio?" % slabs, slabs / 2 - 1, "Servono %d ÷ 2 = %d viaggi in tutto; uno è già concluso, quindi ne restano %d." % [slabs, slabs / 2, slabs / 2 - 1], "Un passaggio senza crolli", "Il varco è libero: le lucertole si spargono fra le iscrizioni protette.", "Distingui il lavoro totale da quello ancora da fare. Prima trovi i viaggi necessari, poi togli quelli già completati."),
			]
		8:
			var amps := 2 + v
			nodes = [
				_mc("elettronica", "guasti", "Nel pannello simulato di Rame, tre rami sono in parallelo. Aprendo A il sovraccarico resta; aprendo B il sovraccarico scompare; aprendo C il sovraccarico resta. Ogni test è stato fatto da solo, ripristinando prima la configurazione iniziale. Quale ramo va isolato?", "B", ["A", "C"], "Solo togliendo B il sovraccarico scompare. I test separati permettono di attribuire l'effetto a quel ramo.", "Il ramo che trascina gli altri", "Il ramo B è isolato. Gli altri rami possono essere verificati.", "Nel modello, aprire un ramo interrompe la corrente soltanto in quel ramo. Per confrontare test, parti ogni volta dalla stessa configurazione e cambia una sola cosa."),
				_num("matematica", "problemi", "Isolato B, restano A e C. Ciascuno assorbe %d A; il limite del generatore è 8 A. Quanti ampere di margine restano con entrambi attivi?" % amps, 8 - 2 * amps, "A e C assorbono insieme 2 × %d A. Il margine è 8 meno quell'assorbimento." % amps, "La capacità che resta", "Il generatore ha margine sufficiente per alimentare A e C insieme.", "Le correnti dei rami si sommano alla sorgente. Il margine è il limite disponibile meno la corrente totale richiesta."),
				_order("coding", "condizioni", "Il margine trovato consente A e C, ma B deve restare aperto. Il controllore deve prima isolare B; può testare A e C soltanto dopo l'isolamento; può confermare il ripristino soltanto dopo il test. Ordina le istruzioni.", ["Apri B e mantienilo aperto", "Attiva A e C per il test", "Conferma il ripristino se il test passa"], "La conferma dipende dal test e il test dipende dall'isolamento. Saltare la prima azione reintroduce il guasto diagnosticato.", "Un ripristino controllato", "Il ronzio si stabilizza: gli isolotti dei rami sani tornano accesi.", "Un controllore deve verificare le condizioni prima delle azioni che ne dipendono. La conferma finale deve poter fallire se il test non passa."),
			]
		9:
			var scale := 2 + v
			nodes = [
				_mc("geografia", "geografia-fisica", "Bussola ha lasciato una carta con nord in alto. Il porto è a ovest della torre; una scogliera chiude la costa nord. La nave deve raggiungere il porto costeggiando solo il lato sud dell'isola. Quale rotta rispetta destinazione e ostacolo?", "Dalla torre vai a sud, poi a ovest, poi a nord verso il porto", ["Dalla torre vai a nord, poi a ovest", "Dalla torre vai a sud, poi a est"], "La prima rotta aggira la scogliera a sud e torna al porto occidentale; le altre violano l'ostacolo o la destinazione.", "La costa da evitare", "La rotta sud-ovest-nord aggira la scogliera e raggiunge il porto.", "Con nord in alto, sud è in basso, ovest a sinistra ed est a destra. Una rotta deve rispettare sia la meta sia gli ostacoli segnati."),
				_num("matematica", "proporzioni", "La rotta scelta misura 2 cm verso sud, 3 cm verso ovest e 2 cm verso nord sulla carta. Ogni centimetro rappresenta %d km. Quanti chilometri percorre la nave lungo questa rotta?" % scale, 7 * scale, "Somma i segmenti della rotta: 2 + 3 + 2 = 7 cm. La distanza percorsa è 7 × %d km, non la sola distanza in linea retta fra torre e porto." % scale, "La distanza reale", "La torre conosce la lunghezza completa della rotta sicura.", "Una scala collega ogni unità sulla carta a una distanza reale. Prima misura il percorso effettivo, poi applica il fattore di scala."),
				_order("coding", "algoritmi", "Programma l'indicatore della torre per la rotta verificata. Il primo segmento aggira la costa verso sud, il secondo porta a ovest, l'ultimo risale al porto. Ordina le istruzioni usando le distanze reali appena calcolate.", ["Vai a sud per %d km" % (2 * scale), "Vai a ovest per %d km" % (3 * scale), "Vai a nord per %d km" % (2 * scale)], "Le lunghezze rispettano la scala; l'ordine evita la scogliera. Avere soltanto la somma giusta non basta per seguire la rotta.", "La carta torna viva", "Il braccio della torre indica la rotta sicura e aggiorna la carta.", "Un algoritmo di navigazione precisa direzione, distanza e ordine. Scambiare due azioni può attraversare un ostacolo pur mantenendo la stessa lunghezza totale."),
			]
		10:
			var plants := 4 + v
			nodes = [
				_mc("scienze", "metodo", "Seme deve capire perché una vasca con alghe e piccoli animali perde ossigeno. Vasca A: luce, 20 °C, ossigeno stabile; B: buio, 20 °C, ossigeno in calo; C: luce, 25 °C, ossigeno in calo. Specie, quantità e durata del test sono uguali. Quale confronto isola l'effetto della luce?", "A con B", ["A con C", "B con C"], "Fra A e B cambia soltanto la luce. A e C differiscono per temperatura; B e C cambiano due condizioni. Il confronto A-B sostiene l'effetto della luce nelle condizioni di questo test.", "Una causa alla volta", "Il confronto indica di ripristinare la luce prima di riaprire le vasche.", "Per studiare una causa confronta due condizioni che differiscono solo per quella variabile. Un risultato non dimostra che la stessa causa spieghi ogni altro caso."),
				_num("matematica", "problemi", "La luce è ripristinata. Nel modello della Serra, ogni gruppo di alghe illuminato aggiunge 3 unità di ossigeno nel periodo; gli animali ne consumano 8 e la vasca parte da 2 unità. Con %d gruppi di alghe, quante unità ci sono alla fine del periodo?" % plants, 2 + 3 * plants - 8, "Bilancio del modello: 2 iniziali + %d × 3 prodotte − 8 consumate = %d. La produzione dipende dalla luce ripristinata." % [plants, 2 + 3 * plants - 8], "Il bilancio della vasca", "Il bilancio permette il test di riapertura senza esaurire l'ossigeno.", "Un bilancio conserva la quantità iniziale, aggiunge le entrate e sottrae le uscite. Qui le unità sono un modello di gioco: i tassi reali dipendono anche dalle condizioni ambientali."),
				_order("scienze", "ecosistema", "Il bilancio è favorevole, ma è una previsione. Seme prescrive di riaprire una paratia, misurare il risultato dopo il periodo di prova e aprire le altre solo se l'ossigeno non cala sotto la soglia. Ordina il piano che verifica il modello.", ["Apri una sola paratia", "Misura l'ossigeno dopo il periodo di prova", "Apri le altre solo se la soglia è rispettata"], "La previsione rende ragionevole il test, ma la misura decide l'estensione. Aprire tutto prima di misurare elimina il controllo graduale.", "Riunire senza indovinare", "Il test conferma il bilancio: le paratie si aprono e la Serra torna collegata.", "In un ecosistema cambiare collegamenti può modificare gli equilibri. Un intervento graduale permette di verificare le conseguenze prima di estenderlo."),
			]
		11:
			var first := 120 + 10 * v
			nodes = [
				_order("storia", "cronologia", "Clessidra ha tre registri riferiti alla stessa città: fondazione nel %d a.C., incendio nel 80 a.C., ricostruzione nel 30 a.C. Ordinali dal più antico al più recente per riallineare il portale." % first, ["Fondazione: %d a.C." % first, "Incendio: 80 a.C.", "Ricostruzione: 30 a.C."], "Negli anni prima di Cristo, un numero più grande indica una data più antica. Avvicinandosi all'inizio dell'era, i numeri diminuiscono.", "Il tempo al contrario", "La fondazione precede l'incendio; la ricostruzione viene dopo.", "Una linea del tempo a.C. scorre per esempio da 90 a.C. a 60 a.C. e poi a 20 a.C. Non ordinare i numeri senza considerare l'era."),
				_num("matematica", "problemi", "Usa le date ordinate: la fondazione è nel %d a.C. e l'incendio nel 80 a.C. Il portale richiede l'intervallo fra questi due eventi, senza aggiungere l'anno iniziale. Quanti anni passano?" % first, first - 80, "Le date sono nella stessa era: la distanza è %d − 80 = %d anni. Non serve attraversare un anno zero." % [first, first - 80], "La distanza fra gli strati", "Il portale è calibrato sull'intervallo fra fondazione e incendio.", "La durata fra due date è la distanza sulla linea del tempo. Fra il 70 a.C. e il 50 a.C. passano venti anni, non ventuno."),
				_mc("storia", "fonti", "Il portale calibrato mostra uno strato di cenere e un registro cittadino dell'80 a.C. che descrive un incendio. Un racconto scritto quattro secoli dopo attribuisce la cenere a un drago. Quale conclusione è sostenuta meglio da queste prove?", "L'incendio è sostenuto dal registro e dallo strato; la causa drago resta non verificata", ["La cenere dimostra che è passato un drago", "Il racconto più recente annulla automaticamente il registro"], "Registro e cenere sono coerenti con un incendio, ma non identificano da soli chi lo ha causato. Un racconto tardivo richiede verifiche indipendenti.", "Una storia sostenuta dalle prove", "Il portale distingue il fatto documentato dalla spiegazione ancora incerta.", "Confronta provenienza, epoca e contenuto delle fonti. Due indizi concordi possono sostenere un evento senza dimostrarne ogni dettaglio o causa."),
			]
		12:
			var initial := 80 + 4 * v
			nodes = [
				_mc("logica", "deduzioni", "Nel cuore del labirinto, tutte le ventole ricevono energia solo se l'interruttore V è chiuso. Il registro dice V aperto; un sensore segnala una ventola accesa. La regola del circuito è verificata. Che cosa possiamo dedurre con certezza?", "Almeno una delle due letture è errata", ["È sicuramente guasto il sensore della ventola", "La ventola può funzionare senza energia"], "Se V è aperto nessuna ventola può essere alimentata. Le letture sono incompatibili, ma non sappiamo ancora quale sia sbagliata.", "Due segnali incompatibili", "Le letture vanno verificate prima di avviare il raffreddamento.", "Se P è necessario per Q, osservare Q insieme a non-P crea una contraddizione. La contraddizione individua un problema nei dati, non sceglie automaticamente quale dato correggere."),
				_order("coding", "algoritmi", "La contraddizione richiede una diagnosi. Il protocollo del cuore impone: rileggi V con un secondo strumento; usa quella lettura per correggere il registro; solo dopo, avvia le ventole se V risulta chiuso. Ordina il protocollo senza basarti sul dato sospetto.", ["Misura V con il secondo strumento", "Correggi il registro usando la misura", "Avvia le ventole solo con V chiuso"], "La misura indipendente viene prima della correzione; l'azione deve dipendere dal registro verificato. La sola contraddizione non autorizzava a scegliere una lettura.", "Verificare prima di agire", "La misura conferma V chiuso: il registro era errato e le ventole possono partire.", "Per correggere un dato sospetto occorre un controllo indipendente. Il programma deve usare il dato verificato, non semplicemente invertire quello vecchio."),
				_num("fisica", "calore", "Le ventole verificate funzionano. Nel modello del cuore, la temperatura parte da %d °C; a ogni ciclo il raffreddamento la riduce di 6 °C, ma il motore ancora attivo la aumenta di 2 °C. La soglia di riposo è 60 °C o meno. Quanti cicli servono almeno?" % initial, (initial - 60) / 4, "Il calo netto è 6 − 2 = 4 °C per ciclo. Servono (%d − 60) ÷ 4 = %d cicli; uno in meno lascerebbe la temperatura sopra la soglia." % [initial, (initial - 60) / 4], "Il primo riposo", "Il cuore raggiunge la soglia di riposo e i muri si fermano.", "Se riscaldamento e raffreddamento agiscono nello stesso intervallo, considera entrambi nel cambiamento netto. Questo modello assume variazioni costanti per ciclo."),
			]
	for index in nodes.size():
		nodes[index]["id"] = "linked-%d-%d-%d" % [world, v, index]
		nodes[index]["difficulty"] = 1 + floori(float(world - 1) / 3.0)
		nodes[index]["challengeLevel"] = world
	return nodes

static func _base(subject: String, topic: String, prompt: String, explanation: String, step: String, output: String, teaching: String) -> Dictionary:
	return {"subject": subject, "topic": topic, "prompt": prompt, "explanation": explanation, "missionStep": step, "missionOutput": output, "missionTeaching": teaching}

static func _num(subject: String, topic: String, prompt: String, answer: int, explanation: String, step: String, output: String, teaching: String) -> Dictionary:
	var node := _base(subject, topic, prompt, explanation, step, output, teaching)
	node.merge({"format": "numeric_input", "answer": str(answer)})
	return node

static func _mc(subject: String, topic: String, prompt: String, answer: String, wrong: Array, explanation: String, step: String, output: String, teaching: String) -> Dictionary:
	var node := _base(subject, topic, prompt, explanation, step, output, teaching)
	node.merge({"format": "multiple_choice", "answer": answer, "options": [wrong[0], answer, wrong[1]]})
	return node

static func _order(subject: String, topic: String, prompt: String, sequence: Array, explanation: String, step: String, output: String, teaching: String) -> Dictionary:
	var node := _base(subject, topic, prompt, explanation, step, output, teaching)
	var scrambled: Array = sequence.duplicate()
	scrambled.reverse()
	node.merge({"format": "ordering", "items": scrambled, "correctOrder": sequence})
	return node

static func _match(subject: String, topic: String, prompt: String, pairs: Array, explanation: String, step: String, output: String, teaching: String) -> Dictionary:
	var node := _base(subject, topic, prompt, explanation, step, output, teaching)
	var mapped: Array = []
	for pair in pairs:
		mapped.append({"left": pair[0], "right": pair[1]})
	node.merge({"format": "matching", "pairs": mapped})
	return node
