extends RefCounted

## Seconda visita: ogni risultato corretto diventa il dato della tappa seguente.
## I vincoli sono della macchina narrativa, non istruzioni per interventi reali.
static func nodes_for(world: int, variant: int = 0) -> Array:
	var v := posmod(variant, 2)
	var nodes: Array = []
	match world:
		13:
			var area := 60 + 20 * v
			var clean := area * 3 / 4
			nodes = [
				_mc("fisica", "metodo", "La lente ha una crosta. Abaco ha provato tre pulizie su porzioni uguali: A toglie la crosta ma graffia; B toglie la crosta senza graffi; C lascia la crosta. Per proiettare le stelle occorre eliminare la crosta E conservare lo specchio. Quale prova autorizza il trattamento?", ["A: pulisce più aggressivamente", "B: soddisfa entrambi i vincoli", "C: non rischia graffi"], "B: soddisfa entrambi i vincoli", "B è l'unica osservazione che soddisfa insieme pulizia e integrità.", "Il trattamento di Abaco", "Usa B solo sulla zona incrostata, che occupa tre quarti della lente.", "Un esperimento confrontabile mantiene uguali porzioni e condizioni, cambiando il trattamento. Prima di scegliere controlla tutti i requisiti, anche gli effetti indesiderati."),
				_num("matematica", "frazioni", "Con il trattamento B pulisci solo i tre quarti incrostati. La superficie totale misura %d unità quadrate. Ogni dose copre 5 unità quadrate. Quante dosi occorrono?" % area, clean / 5, "Calcola prima tre quarti della superficie, poi dividi per la copertura di una dose.", "Dosare senza sprechi", "Servono %d dosi; dopo la pulizia la luce raggiunge lo specchio." % (clean / 5), "Tre quarti significa dividere il totale in quattro parti uguali e prenderne tre. Per ricavare il numero di dosi dividi la superficie da trattare per la superficie coperta da una dose."),
				_order("coding", "algoritmi", "La lente pulita lascia passare la luce. Il sistema registra una mappa solo dopo aver misurato la stella; può misurarla solo a specchio orientato; può orientarsi solo dopo aver acquisito la luce. Ricostruisci le dipendenze per avviare la proiezione.", ["Registrare la mappa", "Orientare lo specchio", "Acquisire la luce", "Misurare la stella"], ["Acquisire la luce", "Orientare lo specchio", "Misurare la stella", "Registrare la mappa"], "Ogni operazione prepara l'ingresso della successiva: luce, orientamento, misura, mappa.", "La prima costellazione", "La mappa delle stelle può essere proiettata sulle dune.", "In un algoritmo una dipendenza impone un ordine: un'operazione che usa un risultato deve attendere che quel risultato esista."),
			]
		14:
			var voices := 18 + 6 * v
			nodes = [
				_mc("italiano", "sintassi", "Stilo ha inciso: «Le voci che provengono dalla sala nord devono attendere; le altre possono uscire». Il registro distingue N (sala nord), E (sala est), O (sala ovest). Quali gruppi autorizza la frase?", ["N soltanto", "E e O soltanto", "N, E e O"], "E e O soltanto", "La relativa «che provengono dalla sala nord» limita l'attesa al gruppo N; «le altre» indica E e O.", "Separare le voci", "Il canale d'uscita riceverà E e O; N resta in attesa.", "Una relativa restrittiva identifica un sottoinsieme: «i messaggi che hanno il sigillo» indica soltanto quelli col sigillo, non tutti i messaggi."),
				_num("matematica", "problemi", "I gruppi autorizzati E e O contengono insieme %d voci. Per distinguerle, la sala lascia uscire 3 voci per turno, senza sovrapporle. Quanti turni completi servono prima di passare a N?" % voices, voices / 3, "Il totale dei turni è il numero delle voci autorizzate diviso per le tre voci di ogni turno.", "Il tempo dell'ascolto", "E e O occuperanno %d turni; poi il canale sarà libero per N." % (voices / 3), "Se ogni turno contiene lo stesso numero di voci, la divisione calcola quanti turni servono. Le voci del gruppo in attesa non entrano nel conto."),
				_order("logica", "deduzioni", "Il canale sarà libero dopo E e O. Ricomponi il protocollo: non si apre N prima della conferma che E e O siano usciti; la conferma richiede l'ascolto; l'ascolto richiede porte E/O aperte. Tutte le operazioni sono necessarie.", ["Aprire N", "Confermare E/O vuoti", "Aprire E/O", "Ascoltare E/O"], ["Aprire E/O", "Ascoltare E/O", "Confermare E/O vuoti", "Aprire N"], "Le condizioni creano un unico ordine: apertura, ascolto, conferma, nuovo gruppo.", "Una voce alla volta", "Le porte rilasciano le voci senza sovrapporle.", "Una condizione necessaria deve essere soddisfatta prima dell'azione: se B richiede A, B non può precedere A."),
			]
		15:
			var target := 48 + 16 * v
			nodes = [
				_mc("coding", "cicli", "Il mulino riparato ha quattro pale. Il programma visita le pale numerate 1, 2, 3, 4, ma oggi torna a 1 dopo la 3. Quale correzione completa un giro senza saltare o contare due volte una pala?", ["Dopo la pala 3 torna a 1", "Dopo la pala 4 torna a 1", "Dopo la pala 4 passa alla pala 5"], "Dopo la pala 4 torna a 1", "Il giro deve comprendere tutte e sole le pale 1–4; il ritorno a 1 avviene dopo la quarta.", "Chiudere il ciclo", "Ogni giro comprende ora quattro spinte, una per pala.", "Il confine di un ciclo stabilisce quali elementi vengono eseguiti. Un arresto troppo presto ne salta uno; troppo tardi tenta un elemento inesistente."),
				_num("matematica", "proporzioni", "Il ciclo corretto usa quattro pale; ciascuna sposta 2 litri per giro. La rete bassa richiede %d litri. Quanti giri completi devi programmare?" % target, target / 8, "Quattro pale per 2 litri producono 8 litri per giro; dividi il fabbisogno per 8.", "L'acqua per la rete", "Programma %d giri completi, con due litri per pala." % (target / 8), "Prima ricava la portata di un giro moltiplicando pale per litri di ogni pala. Poi rapporta il volume necessario a quella portata."),
				_matching("fisica", "metodo", "Il programma è fissato a %d giri. Ora controlla se le quattro pale lavorano davvero allo stesso modo. Per ciascuna osservazione scegli che cosa consente di concludere: una misura del solo totale può nascondere squilibri." % (target / 8), [{"left": "Ogni pala sposta 2 litri", "right": "Portate uguali e obiettivo rispettato"}, {"left": "Pale: 1, 3, 2, 2 litri", "right": "Totale giusto ma pale sbilanciate"}, {"left": "Misurato soltanto: 8 litri totali", "right": "Equilibrio delle pale ancora da verificare"}], "La stessa somma può derivare da contributi diversi: per verificare l'equilibrio occorre misurare ogni pala.", "Un giro davvero regolare", "Il collaudo distingue portata totale ed equilibrio; il mulino torna a servire la rete bassa.", "Una misura aggregata non descrive sempre le sue parti. Controllare un totale e controllare la distribuzione risponde a due domande diverse."),
			]
		16:
			var cap := 18 + 6 * v
			nodes = [
				_matching("inglese", "conditionals", "Il pannello di Faro controlla tre automi del mercato. Traduci le conseguenze delle condizioni per poter confrontare le rotte dei serbatoi.", [{"left": "If the east gate is blocked, use the west gate.", "right": "Est bloccato: usare il passaggio ovest"}, {"left": "Unless the tank is full, wait.", "right": "Serbatoio non pieno: attendere"}, {"left": "If the signs are protected, open the market.", "right": "Insegne protette: riaprire il mercato"}], "If introduce una condizione; unless significa «a meno che» e qui equivale a «se non».", "Le condizioni di Faro", "Il passaggio est è bloccato: confronta solo le rotte ovest, con serbatoi pieni.", "If A, B significa «se A, allora B». Unless A, B significa «se non A, allora B». Full = pieno; blocked = bloccato; signs = insegne; wait = attendi."),
				_num("matematica", "problemi", "Devi consegnare %d unità d'acqua con serbatoi da 6. A ovest, la rotta breve costa 2 minuti per viaggio ma il ponte ammette solo serbatoi da 3; la rotta larga costa 3 minuti e ammette quelli da 6. I tempi includono il ritorno. Quanti minuti richiede la strategia più veloce?" % cap, cap / 2, "Breve: (%d ÷ 3) × 2 = %d minuti. Larga: (%d ÷ 6) × 3 = %d minuti: conviene la larga." % [cap, cap * 2 / 3, cap, cap / 2], "Scegliere con due vincoli", "La rotta larga consegna l'acqua in %d minuti e rispetta il limite del ponte." % (cap / 2), "Confronta il tempo totale, non solo il singolo viaggio: numero di viaggi × durata. Una rotta più breve può richiedere più viaggi se trasporta meno."),
				_order("logica", "deduzioni", "La rotta larga è scelta. Il pannello permette di riaprire il mercato solo con insegne protette; la protezione richiede l'acqua consegnata; la consegna richiede l'autorizzazione della rotta. Ordina i comandi degli automi.", ["Riaprire il mercato", "Consegnare l'acqua", "Autorizzare la rotta larga", "Proteggere le insegne"], ["Autorizzare la rotta larga", "Consegnare l'acqua", "Proteggere le insegne", "Riaprire il mercato"], "Il piano rispetta le condizioni del pannello e usa la strategia confrontata nella tappa precedente.", "Il valico riapre", "Gli automi proteggono le insegne e riaprono il mercato.", "Un piano è valido solo se ogni azione trova già vere le condizioni che richiede."),
			]
		17:
			var resistance := 120 + 40 * v
			nodes = [
				_num("fisica", "leve", "La rete è impigliata. Nel modello di Leva, per iniziare a sollevarla la forza × braccio motore deve uguagliare resistenza × braccio resistente. La resistenza è %d unità e il suo braccio misura 1; il braccio motore misura 4. Qual è la forza minima richiesta?" % resistance, resistance / 4, "%d × 1 ÷ 4 = %d. Il braccio più lungo riduce la forza richiesta nel modello." % [resistance, resistance / 4], "Misurare lo sforzo", "Il braccio da 4 richiede %d unità di forza." % (resistance / 4), "Nel modello ideale della leva conta il prodotto forza × distanza dal fulcro. All'equilibrio i due prodotti sono uguali: F × braccio motore = resistenza × braccio resistente."),
				_mc("matematica", "disequazioni", "Disponi di %d unità di forza. Il braccio da 4 appena calcolato ne richiede %d, quello da 2 ne richiede %d. Il corridoio consente al massimo lunghezza 4. Quale scelta rispetta spazio e forza?" % [resistance / 4 + 5, resistance / 4, resistance / 2], ["Braccio da 2: occupa meno spazio", "Braccio da 4: rispetta entrambi i limiti", "Braccio da 6: più lungo è sempre ammesso"], "Braccio da 4: rispetta entrambi i limiti", "Il braccio da 2 supera la forza disponibile; quello da 6 supera lo spazio. Quello da 4 soddisfa tutte e due le disuguaglianze.", "La strategia possibile", "La leva da 4 è compatibile; manca predisporre l'uscita degli animali.", "Un'opzione è ammissibile se rispetta contemporaneamente tutti i limiti. Basta violarne uno per escluderla."),
				_order("scienze", "ambiente", "La leva scelta solleverà la rete. Gli animali non devono restare intrappolati quando la si recupera: il varco va aperto prima del sollevamento; la verifica degli animali può avvenire solo dopo il sollevamento; il recupero richiede la rete vuota. Pianifica.", ["Recuperare la rete vuota", "Sollevare con la leva da 4", "Aprire il varco", "Verificare l'uscita degli animali"], ["Aprire il varco", "Sollevare con la leva da 4", "Verificare l'uscita degli animali", "Recuperare la rete vuota"], "Il piano unisce il vincolo meccanico con quello ambientale: recuperare l'attrezzo senza trascinare gli animali.", "Recuperare senza catturare", "La rete sale vuota; gli animali restano attorno alla cattedrale.", "Una soluzione tecnica va verificata anche per i suoi effetti sugli esseri viventi: riuscire a muovere un oggetto non garantisce di averli liberati."),
			]
		18:
			var beats := 12 + 4 * v
			nodes = [
				_num("musica", "tempo", "L'organo riempie una camera d'aria ogni battuta di quattro pulsazioni. Corda confronta un comando ogni pulsazione con uno ogni battuta: basta una camera per battuta. In %d pulsazioni, quanti comandi di riempimento servono senza sprechi?" % beats, beats / 4, "Raggruppa le pulsazioni a quattro: %d ÷ 4 = %d battute, quindi altrettanti riempimenti." % [beats, beats / 4], "Il respiro dell'organo", "Servono %d riempimenti, uno ogni quattro pulsazioni." % (beats / 4), "La pulsazione è il battito regolare; qui una battuta ne raggruppa quattro. Un evento per battuta avviene meno spesso di un evento per pulsazione."),
				_matching("coding", "cicli", "Per ottenere i %d riempimenti calcolati, confronta questi programmi sullo stesso intervallo di %d pulsazioni. Assegna a ogni strategia il suo effetto." % [beats / 4, beats], [{"left": "Riempire a ogni pulsazione", "right": "Quattro volte il necessario"}, {"left": "Riempire alla quarta pulsazione di ogni gruppo di quattro", "right": "Un riempimento per battuta"}, {"left": "Riempire soltanto alla fine di tutto l'intervallo", "right": "Una sola camera: insufficiente"}], "Il ciclo interno conta quattro pulsazioni; il ciclo esterno ripete le battute. Confondere i due livelli cambia la frequenza del comando.", "Il ciclo che respira", "Il programma scelto riempie una camera ogni battuta.", "Nei cicli annidati distingui ciò che accade a ogni passo interno da ciò che accade al termine di un gruppo."),
				_mc("fisica", "metodo", "Con il ciclo corretto, la canna A resta muta e B suona. Scambiando solo le valvole, A suona e B diventa muta. Quale intervento è sostenuto da questo confronto?", ["Cambiare il tempo di tutto l'organo", "Riparare la valvola che ora è su B", "Sostituire entrambe le canne"], "Riparare la valvola che ora è su B", "Il difetto segue la valvola, mentre il ciclo resta uguale: il confronto localizza lì il guasto.", "Trovare la voce mancante", "La valvola difettosa è individuata; le canne possono tornare a suonare insieme.", "Per distinguere due cause, cambia un componente alla volta. Se il difetto si sposta insieme al componente, hai un indizio causale da verificare riparandolo."),
			]
		19:
			nodes = [
				_matching("latino", "casi", "Radice ha etichettato i canali: «radix aquam quaerit», «aqua radicem nutrit», «canalis radicem ducit». Individua l'azione di ciascun soggetto per riconoscere il canale che guida la radice, anziché fermarla.", [{"left": "radix aquam quaerit", "right": "La radice cerca l'acqua"}, {"left": "aqua radicem nutrit", "right": "L'acqua nutre la radice"}, {"left": "canalis radicem ducit", "right": "Il canale guida la radice"}], "Radix e aqua sono soggetti nelle prime due frasi; aquam e radicem sono oggetti. Il terzo cartello identifica il canale guida.", "Leggere le radici", "Il canale segnato «canalis radicem ducit» è quello da esaminare.", "In queste frasi radix = radice, aqua = acqua, canalis = canale. Aquam/radicem indicano l'oggetto dell'azione; quaerit = cerca, nutrit = nutre, ducit = guida. La desinenza aiuta a distinguere chi agisce da chi riceve l'azione."),
				_mc("scienze", "metodo", "Nel canale guida le radici si dirigono verso una parete umida, sollevando la cripta. Per verificare se l'umidità le orienta, quale confronto prepara Radice?", ["Due tratti con luce e terreno uguali, ma umidità diversa", "Due tratti diversi per luce, terreno e umidità", "Un solo tratto, senza misurare la crescita"], "Due tratti con luce e terreno uguali, ma umidità diversa", "Variare solo l'umidità permette di attribuirle con più fondamento l'eventuale differenza. L'esito va osservato, non dato per certo.", "Verificare prima di deviare", "La prova osservata mostra crescita verso il tratto umido: il nuovo percorso userà questa indicazione.", "Un'ipotesi suggerisce cosa confrontare. Mantieni costanti le altre condizioni e registra l'esito; una singola osservazione non dimostra una regola universale."),
				_order("logica", "deduzioni", "La prova favorisce il tratto umido. Per proteggere l'albero, il vecchio percorso resta disponibile fino alla verifica del nuovo. Per osservare crescita nel nuovo canale occorre prima irrigarlo; l'acqua può entrare solo a canale liberato. Ricostruisci il piano.", ["Chiudere il vecchio percorso", "Irrigare il nuovo canale", "Verificare la crescita nel nuovo canale", "Liberare il nuovo canale"], ["Liberare il nuovo canale", "Irrigare il nuovo canale", "Verificare la crescita nel nuovo canale", "Chiudere il vecchio percorso"], "Prima si rende praticabile l'alternativa, poi la si verifica, infine si abbandona il vecchio percorso.", "Salvare albero e archivio", "Le radici seguono i canali predisposti e le cripte possono richiudersi.", "Un piano con verifica conserva una via funzionante finché l'alternativa non è stata osservata in azione."),
			]
		20:
			var charge := 72 + 24 * v
			nodes = [
				_matching("elettronica", "guasti", "Nel simulatore di Rame, ogni segmento conduce solo se il suo indicatore è verde. Torre verso A è verde; A verso B è rosso; B verso terra è verde. Associa le prove alle conclusioni, prima di scegliere la riparazione virtuale.", [{"left": "Torre-A verde", "right": "Ingresso del percorso continuo"}, {"left": "A-B rosso", "right": "Interruzione da riparare"}, {"left": "B-terra verde", "right": "Uscita continua ma insufficiente da sola"}], "Un percorso richiede continuità in tutti i segmenti: l'uscita verde non compensa il segmento A-B interrotto.", "Seguire il percorso intero", "Ripara A-B nel simulatore; poi verifica l'intero percorso dalla torre alla terra.", "Un circuito completo richiede un percorso continuo. Il controllo locale di un solo tratto non dimostra la continuità dell'intero collegamento. Qui si opera esclusivamente sul pannello simulato."),
				_num("matematica", "problemi", "Il percorso riparato smaltisce nel simulatore 12 unità per ciclo; la tempesta ne aggiunge 4 nello stesso ciclo. La torre contiene %d unità e deve scendere a 24. Quanti cicli servono?" % charge, (charge - 24) / 8, "Ogni ciclo toglie in netto 12 − 4 = 8. Occorre rimuovere %d − 24 = %d unità, quindi %d cicli." % [charge, charge - 24, (charge - 24) / 8], "Considerare anche l'ingresso", "Il bilancio prevede %d cicli per raggiungere 24 unità." % ((charge - 24) / 8), "Quando entrate e uscite avvengono insieme, il cambiamento netto è uscita meno entrata. Usare solo l'uscita sovrastima la velocità di svuotamento."),
				_mc("coding", "condizioni", "Il calcolo porta la torre alla soglia di 24. Il pannello deve fermare la sequenza soltanto con carica ≤ 24 E percorso continuo. Quale condizione rispetta entrambi i requisiti?", ["carica ≤ 24 OR continuo", "carica ≤ 24 AND continuo", "carica > 24 AND continuo"], "carica ≤ 24 AND continuo", "AND richiede entrambe le condizioni; OR consentirebbe l'arresto anche con uno dei due requisiti falso.", "Confermare la stabilità", "La sequenza verifica soglia e continuità prima di dichiarare stabile la torre.", "AND è vero solo se entrambe le condizioni sono vere. OR è vero anche se lo è soltanto una. Il confronto ≤ include anche l'uguaglianza."),
			]
		21:
			var width := 6 + 2 * v
			nodes = [
				_mc("geografia", "geografia-fisica", "Bussola registra le frecce di due placche: quella a ovest va verso ovest, quella a est verso est. Nel modello del pilastro, quale movimento devono tollerare i cerchi senza fingere di arrestare le placche reali?", ["Avvicinamento delle placche", "Allontanamento delle placche", "Placche ferme"], "Allontanamento delle placche", "Le frecce puntano via dal confine comune: il margine è divergente. Il pilastro è una macchina fantastica; nella realtà un sostegno non ferma le placche.", "Leggere la faglia", "Il progetto deve compensare un'apertura, non una compressione.", "Un margine divergente separa due placche; convergente le avvicina. Leggi il movimento rispetto al confine, non soltanto il nome di una direzione."),
				_num("matematica", "funzioni", "La compensazione deve coprire l'apertura prevista: oggi %d millimetri, aumento costante di 2 millimetri per anno nel modello. La prossima verifica è fra 3 anni e serve un margine aggiuntivo di 4 millimetri. Quale apertura massima deve tollerare ciascun cerchio?" % width, width + 10, "Apertura futura = %d + 2 × 3; aggiungi poi 4 di margine: %d millimetri." % [width, width + 10], "Dimensionare per il futuro", "Ogni cerchio deve tollerare %d millimetri prima della verifica." % (width + 10), "Una crescita costante si modella come valore iniziale + incremento × tempo. Il margine si aggiunge al valore previsto, non all'incremento annuale."),
				_order("coding", "algoritmi", "I cerchi sono dimensionati a %d millimetri. Il protocollo virtuale vieta di caricare il pilastro prima del collaudo; il collaudo richiede tutti e tre i cerchi; il montaggio richiede aver scaricato il modello. Ordina le operazioni." % (width + 10), ["Applicare il carico", "Montare i tre cerchi", "Scaricare il modello", "Collaudare i tre cerchi"], ["Scaricare il modello", "Montare i tre cerchi", "Collaudare i tre cerchi", "Applicare il carico"], "Il piano integra previsione e dipendenze: il componente dimensionato viene verificato prima dell'uso.", "Il pilastro torna a reggere", "I tre cerchi superano il collaudo e sostengono il pilastro del mondo.", "Un algoritmo operativo include precondizioni e verifica: preparare un componente non basta per considerarlo funzionante."),
			]
		22:
			var oxygen := 30 + 6 * v
			nodes = [
				_matching("scienze", "metodo", "Seme deve verificare se aprire la paratia migliora lo scambio del nucleo. Associa ciascun risultato alla conclusione sostenibile: osservazioni e spiegazioni non sono la stessa cosa.", [{"left": "Si apre solo la paratia; ossigeno sale e temperatura resta stabile", "right": "Indizio favorevole allo scambio attraverso la paratia"}, {"left": "Si aprono paratia e ventilatore insieme; ossigeno sale", "right": "Non si distingue quale intervento abbia causato l'aumento"}, {"left": "Paratia aperta; nessuna misura registrata", "right": "Mancano dati per valutare l'effetto"}], "Il primo confronto isola l'intervento; il secondo confonde due cause; il terzo non permette una verifica.", "Scegliere una prova interpretabile", "La prova isolata misura un ingresso di 8 unità d'ossigeno e un consumo di 2 per minuto.", "Per sostenere una spiegazione servono dati e un confronto che distingua le cause possibili. Un miglioramento osservato dopo due cambiamenti non identifica da solo la causa."),
				_num("matematica", "equazioni", "La prova isolata fornisce ingresso 8 e consumo 2 unità al minuto. Il nucleo parte da %d e deve raggiungere 60. Nel modello i flussi restano costanti: per quanti minuti devi mantenere questa apertura?" % oxygen, (60 - oxygen) / 6, "Risolvi %d + (8 − 2)t = 60: l'incremento netto è 6 al minuto, quindi t = %d." % [oxygen, (60 - oxygen) / 6], "Prevedere la riapertura", "Il piano prevede %d minuti di apertura, con verifica finale dei sensori." % ((60 - oxygen) / 6), "Un'equazione esprime il traguardo: quantità iniziale + crescita netta × tempo = quantità desiderata. La previsione vale finché le ipotesi sui flussi restano valide."),
				_mc("logica", "deduzioni", "Il tempo previsto è trascorso, ma il sensore indica 54 invece di 60; la temperatura è stabile. Il piano richiede ossigeno almeno 60 e temperatura stabile. Quale decisione è giustificata?", ["Dichiarare riuscita l'apertura perché il tempo calcolato è passato", "Mantenere il controllo e riesaminare i flussi: manca un requisito", "Chiudere per sempre: una previsione sbagliata rende inutili tutte le misure"], "Mantenere il controllo e riesaminare i flussi: manca un requisito", "Una previsione dipende dalle ipotesi. La misura mostra che la soglia non è raggiunta: occorre verificare il modello e continuare il controllo prima della liberazione.", "Una decisione motivata", "Il protocollo richiede entrambi i sensori conformi prima di liberare il nucleo.", "Confronta previsione e misura. Se divergono, non sostituire il dato con il calcolo: riesamina le ipotesi e verifica di nuovo le condizioni di successo."),
			]
		23:
			var first := 140 + 10 * v
			nodes = [
				_matching("storia", "fonti", "Clessidra confronta documenti dell'archivio immaginario. Associa ogni fonte alla domanda a cui risponde più direttamente, senza trattare una previsione come un fatto avvenuto.", [{"left": "Registro di consegna firmato nell'anno %d" % first, "right": "Quando arrivarono i componenti?"}, {"left": "Progetto: apertura prevista due anni dopo la consegna", "right": "Quando si intendeva aprire?"}, {"left": "Verbale: apertura effettiva cinque anni dopo la consegna", "right": "Quando risulta avvenuta l'apertura?"}], "Il progetto testimonia un'intenzione; il verbale registra l'evento; la consegna fissa il riferimento temporale. Le fonti rispondono a domande differenti.", "Interrogare le fonti", "La consegna è nell'anno %d; apertura prevista +2, effettiva +5." % first, "Per valutare una fonte chiedi chi l'ha prodotta, per quale scopo e su quale evento dà informazioni. Una data prevista non prova che l'evento sia avvenuto allora."),
				_num("matematica", "problemi", "Usando le fonti: consegna nell'anno %d, apertura prevista due anni dopo, effettiva cinque anni dopo. Il ritardo era tollerato per un massimo di un anno rispetto al progetto. Di quanti anni il ritardo effettivo supera la tolleranza?" % first, 2, "Il ritardo rispetto al progetto è 5 − 2 = 3 anni; tolto l'anno tollerato, l'eccedenza è 2 anni.", "Misurare lo scarto", "L'apertura supera la tolleranza di due anni; i documenti non ne dicono ancora la causa.", "Distingui tre riferimenti: data dell'evento, ritardo rispetto al piano ed eccedenza rispetto alla tolleranza. Non sono la stessa quantità."),
				_mc("italiano", "tipologie-testuali", "Devi scrivere la sintesi che accende la sala. Hai dimostrato due anni oltre la tolleranza, ma nessuna fonte spiega la causa. Quale frase distingue fatti e limiti delle prove?", ["L'apertura superò la tolleranza di due anni; dai documenti letti non sappiamo perché.", "L'apertura fu sabotata: ogni ritardo dimostra un sabotaggio.", "Il progetto prova che l'archivio aprì nella data prevista."], "L'apertura superò la tolleranza di due anni; dai documenti letti non sappiamo perché.", "La prima sintesi riporta il risultato sostenuto dalle fonti e rende esplicito ciò che resta ignoto. Le altre aggiungono una causa non provata o confondono piano ed evento.", "Una conclusione onesta", "Le fonti si illuminano a coppie; la sintesi conserva anche la domanda ancora aperta.", "In una sintesi argomentata distingui ciò che i documenti attestano, ciò che inferisci e ciò che non puoi ancora stabilire."),
			]
		24:
			var load_value := 96 + 12 * v
			nodes = [
				_matching("logica", "deduzioni", "Il Cuore ha quattro configurazioni virtuali. È ammissibile solo se il raffreddamento resta acceso E il carico non supera 72. Classifica le tre proposte dei sistemi prima di progettare quella definitiva.", [{"left": "A: carico 60, raffreddamento spento", "right": "Viola il requisito di raffreddamento"}, {"left": "B: carico 84, raffreddamento acceso", "right": "Viola il limite di carico"}, {"left": "C: carico 72, raffreddamento acceso", "right": "Rispetta entrambi i requisiti"}], "Né un carico basso senza raffreddamento né il solo raffreddamento sono sufficienti. C soddisfa la congiunzione delle condizioni.", "Le condizioni dei Dodici", "La configurazione obiettivo mantiene il raffreddamento e porta il carico a 72.", "Per dimostrare che una scelta soddisfa A E B devi verificare entrambi. Un controesempio a una sola condizione basta a scartarla."),
				_num("matematica", "equazioni", "Il carico attuale è %d. Ogni gruppo secondario che metti in pausa riduce il carico di 6, senza toccare il raffreddamento. Quanti gruppi devi sospendere per raggiungere esattamente il valore 72 scelto?" % load_value, (load_value - 72) / 6, "Risolvi %d − 6g = 72: g = (%d − 72) ÷ 6 = %d. Il raffreddamento è escluso dai gruppi sospendibili." % [load_value, load_value, (load_value - 72) / 6], "Ridurre senza spegnere il Cuore", "Il piano sospende %d gruppi secondari e conserva il raffreddamento." % ((load_value - 72) / 6), "Un'equazione può trovare un numero di azioni: stato iniziale − effetto per azione × azioni = obiettivo. Poi verifica che le azioni siano ammesse dai vincoli."),
				_mc("coding", "condizioni", "Hai un piano per arrivare a 72 senza togliere il raffreddamento. Quale controllo finale giustifica davvero il messaggio «Cuore stabile», anche se un gruppo non risponde al comando di pausa?", ["Mostrare stabile dopo aver inviato tutti i comandi: il calcolo basta", "Leggere carico e raffreddamento; mostrare stabile solo se carico ≤ 72 AND raffreddamento acceso", "Leggere solo il numero di comandi inviati e confrontarlo con il piano"], "Leggere carico e raffreddamento; mostrare stabile solo se carico ≤ 72 AND raffreddamento acceso", "I comandi descrivono ciò che chiediamo; i sensori ciò che è accaduto. Il controllo verifica entrambi i vincoli sull'esito e intercetta una pausa non eseguita.", "Il Cuore resta vivo", "Il controllo verifica l'esito del piano: il Cuore resta acceso alla sua temperatura.", "Un programma robusto distingue richiesta ed esito. Dopo l'azione verifica la postcondizione sui dati osservati, soprattutto quando un comando può non essere eseguito."),
			]
	for i in nodes.size():
		var node: Dictionary = nodes[i]
		node["id"] = "linked-%d-%d-%d" % [world, v, i]
		node["difficulty"] = 1 + floori(float(world - 1) / 3.0)
		node["challengeLevel"] = world
	return nodes

static func _base(subject: String, topic: String, prompt: String, explanation: String, step: String, output: String, teaching: String) -> Dictionary:
	return {"subject": subject, "topic": topic, "prompt": prompt, "explanation": explanation, "missionStep": step, "missionOutput": output, "missionTeaching": teaching}

static func _num(subject: String, topic: String, prompt: String, answer: int, explanation: String, step: String, output: String, teaching: String) -> Dictionary:
	var node := _base(subject, topic, prompt, explanation, step, output, teaching)
	node.merge({"format": "numeric_input", "answer": str(answer)})
	return node

static func _mc(subject: String, topic: String, prompt: String, options: Array, answer: String, explanation: String, step: String, output: String, teaching: String) -> Dictionary:
	var node := _base(subject, topic, prompt, explanation, step, output, teaching)
	node.merge({"format": "multiple_choice", "options": options, "answer": answer})
	return node

static func _order(subject: String, topic: String, prompt: String, items: Array, correct: Array, explanation: String, step: String, output: String, teaching: String) -> Dictionary:
	var node := _base(subject, topic, prompt, explanation, step, output, teaching)
	node.merge({"format": "ordering", "items": items, "correctOrder": correct})
	return node

static func _matching(subject: String, topic: String, prompt: String, pairs: Array, explanation: String, step: String, output: String, teaching: String) -> Dictionary:
	var node := _base(subject, topic, prompt, explanation, step, output, teaching)
	node.merge({"format": "matching", "pairs": pairs})
	return node
